### ISSUE TITLE
Mac terminal color cast

### ISSUE THREAD

**Issue by NSLog0** [yuttie/hydrangea-vim#1]
I used vim on Mac terminal and color is not like your screenshot. Do you have terminal profile or any suggestion to fix color

**Comment by yuttie** [comment]
@avatarr Ah, sorry, the screenshot has not been updated yet because I'm tuning monochrome colors in the master branch.

I'm sorry for the inconvenience.  I will change the way of my work after the next release.  The master branch would always have a released content, and I will make any changes on a separate branch, possibly named as 'experimental', until a new release is made.

Before that, you can stick to the version of the tag `v4.1` to get the same appearance as the screenshot.
If it doesn't fix your problem, please tell me again.

Thank you for your interest in my theme! :)

**Comment by teejK** [comment]
@yuttie I'm getting these colors with v4.1. Not sure if I'm doing something wrong?

![image](https://user-images.githubusercontent.com/8742739/31234382-b31da0e2-a9e6-11e7-8556-814099f0f080.png)
